apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: otel-dotnet-example
build:
  artifacts:
    - image: tsyltestregistry.azurecr.io/otel-example
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/*.yml
portForward:
  - resourceType: deployment
    resourceName: mywebapp
    namespace: default
    port: 8080
    localPort: 9000 # *Optional
  # - resourceType: deployment
  #   resourceName: kube-prometheus-stack-grafana
  #   namespace: kube-prometheus-stack
  #   port: 3000
  - resourceType: service
    resourceName: grafana
    namespace: observability
    port: 80
    localPort: 9191
