apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mywebapp
  name: mywebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mywebapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mywebapp
    spec:
      containers:
        - image: tsyltestregistry.azurecr.io/otel-example
          imagePullPolicy: IfNotPresent
          name: myapp
          ports:
            - containerPort: 8080
          resources: {}
status: {}
