apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: ClusterIP # or NodePort, LoadBalancer, etc.
  selector:
    app: mywebapp
  labels:
    kfwd: true
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
